version: '3'
services:
  my-python-app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./output:/output
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1